sonar.organization=rueliii
sonar.projectKey=ruelIII_maonanipart
sonar.host.url=https://sonarcloud.io

# This tells SonarQube to scan your Flutter (lib) and PHP (app) folders
sonar.sources=lib,app

# This tells SonarQube the project is in Dart/Flutter and PHP
sonar.language=dart,php
sonar.sourceEncoding=UTF-8
